-- Dokumentations-Snapshot des verifizierten Produktionsschemas
-- Projekt: yknuhfwwuivhfstrawyx, geprüft am 2026-07-15.
-- Diese Datei ist absichtlich nicht ausführbar: Das Backend war bereits
-- eingerichtet, und eine erneute Schemaerzeugung dürfte keine Daten verändern.
--
-- public.profiles
--   id uuid primary key -> auth.users(id); display_name text NULL;
--   timezone text NOT NULL default 'Europe/Berlin'; created_at/updated_at timestamptz;
--   revision bigint NOT NULL default 1.
-- public.user_settings
--   user_id uuid primary key -> auth.users(id); weekday_targets jsonb NOT NULL;
--   automatic_break_enabled boolean NOT NULL default true; locale text NOT NULL default 'de-DE';
--   created_at/updated_at timestamptz; revision bigint NOT NULL default 1.
-- public.projects
--   id uuid primary key; user_id uuid NOT NULL -> auth.users(id); name text NOT NULL;
--   customer/address/color/note text NULL; is_archived boolean NOT NULL default false;
--   created_at/updated_at/deleted_at timestamptz; revision bigint NOT NULL default 1.
-- public.time_entries
--   id uuid primary key; user_id uuid NOT NULL -> auth.users(id); project_id uuid NULL -> projects(id);
--   project_name_snapshot text NOT NULL; entry_type text CHECK(work,vacation,sick,holiday,other_absence);
--   work_date date NOT NULL; started_at/ended_at timestamptz NULL; manual_break_minutes integer default 0;
--   automatically_added_break_minutes integer default 0; activity/note text NULL;
--   source text CHECK(clock,manual,migration,import) default 'clock';
--   created_at/updated_at/deleted_at timestamptz; revision bigint NOT NULL default 1.
-- public.time_breaks
--   id uuid primary key; user_id uuid NOT NULL -> auth.users(id);
--   time_entry_id uuid NOT NULL -> time_entries(id); started_at timestamptz NOT NULL;
--   ended_at/created_at/updated_at/deleted_at timestamptz; revision bigint NOT NULL default 1.
--
-- RLS is enabled for all five tables. Each table has separate ownership policies:
-- SELECT/INSERT/UPDATE/DELETE on user_id = auth.uid(), profiles on id = auth.uid().
-- Existing trigger functions validate project/break ownership; set updated_at and revision;
-- and create profile/settings after auth.users INSERT.
-- Existing uniqueness guarantees: one running work entry per user and one open pause per entry.
-- Realtime publication contains projects, time_entries, time_breaks and user_settings.
