-- Dokumentation des bereits eingerichteten Zeitstempel-Backends.
-- Nicht destruktiv: keine bestehenden Daten werden gelöscht.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,display_name text not null default '',timezone text not null default 'Europe/Berlin',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),revision bigint not null default 0);
create table if not exists public.user_settings (user_id uuid primary key references auth.users(id) on delete cascade,weekday_targets jsonb not null default '{"0":0,"1":480,"2":480,"3":480,"4":480,"5":480,"6":0}'::jsonb,automatic_break_enabled boolean not null default true,locale text not null default 'de-DE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),revision bigint not null default 0);
create table if not exists public.projects (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,customer text not null default '',address text not null default '',color text not null default '#34765f',note text not null default '',is_archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,revision bigint not null default 0);
create table if not exists public.time_entries (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,project_id uuid references public.projects(id),project_name_snapshot text not null default 'Ohne Baustelle',entry_type text not null check(entry_type in ('work','vacation','sick','holiday','other_absence')),work_date date not null,started_at timestamptz,ended_at timestamptz,manual_break_minutes integer not null default 0 check(manual_break_minutes>=0),automatically_added_break_minutes integer not null default 0 check(automatically_added_break_minutes>=0),activity text not null default '',note text not null default '',source text not null check(source in ('clock','manual','migration','import')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,revision bigint not null default 0);
create table if not exists public.time_breaks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,time_entry_id uuid not null references public.time_entries(id),started_at timestamptz not null,ended_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,revision bigint not null default 0);
create unique index if not exists one_open_entry_per_user on public.time_entries(user_id) where ended_at is null and deleted_at is null and entry_type='work';
create unique index if not exists one_open_break_per_entry on public.time_breaks(time_entry_id) where ended_at is null and deleted_at is null;
create or replace function public.touch_revision() returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now();new.revision=old.revision+1;return new;end $$;
do $$ begin foreach tbl in array array['profiles','user_settings','projects','time_entries','time_breaks'] loop execute format('drop trigger if exists touch_revision on public.%I',tbl);execute format('create trigger touch_revision before update on public.%I for each row execute function public.touch_revision()',tbl);end loop;end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name','')) on conflict do nothing;insert into public.user_settings(user_id) values(new.id) on conflict do nothing;return new;end $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.validate_project_owner() returns trigger language plpgsql security invoker set search_path='' as $$ begin if new.project_id is not null and not exists(select 1 from public.projects p where p.id=new.project_id and p.user_id=new.user_id) then raise exception 'Projekt gehört nicht zum Benutzer';end if;return new;end $$;
create or replace function public.validate_break_owner() returns trigger language plpgsql security invoker set search_path='' as $$ begin if not exists(select 1 from public.time_entries e where e.id=new.time_entry_id and e.user_id=new.user_id and e.entry_type='work' and e.deleted_at is null) then raise exception 'Ungültiger Arbeitszeiteintrag';end if;return new;end $$;
drop trigger if exists validate_project_owner on public.time_entries;create trigger validate_project_owner before insert or update on public.time_entries for each row execute function public.validate_project_owner();
drop trigger if exists validate_break_owner on public.time_breaks;create trigger validate_break_owner before insert or update on public.time_breaks for each row execute function public.validate_break_owner();
alter table public.profiles enable row level security;alter table public.user_settings enable row level security;alter table public.projects enable row level security;alter table public.time_entries enable row level security;alter table public.time_breaks enable row level security;
do $$ declare tbl text;begin foreach tbl in array array['profiles','user_settings','projects','time_entries','time_breaks'] loop execute format('drop policy if exists own_rows on public.%I',tbl);if tbl='profiles' then execute 'create policy own_rows on public.profiles for all using (id=auth.uid()) with check (id=auth.uid())';else execute format('create policy own_rows on public.%I for all using (user_id=auth.uid()) with check (user_id=auth.uid())',tbl);end if;end loop;end $$;
do $$ declare tbl text;begin foreach tbl in array array['projects','time_entries','time_breaks','user_settings'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=tbl) then execute format('alter publication supabase_realtime add table public.%I',tbl);end if;end loop;end $$;
